const r = (id, name, team, edition, summary, opts = {}) => ({
  id,
  name,
  team,
  edition,
  summary,
  difficulty: opts.difficulty ?? 2,
  night: opts.night ?? 0,
  evil: opts.evil ?? 0,
  info: opts.info ?? 0,
  setup: opts.setup ?? false,
  tags: opts.tags ?? []
});

export const TEAM_LABELS = {
  townsfolk: 'Townsfolk',
  outsider: 'Outsider',
  minion: 'Minion',
  demon: 'Demon',
  traveller: 'Traveller',
  fabled: 'Fabled / Regra',
  loric: 'Loric / Regra'
};

export const EDITION_LABELS = {
  tb: 'Trouble Brewing',
  bmr: 'Bad Moon Rising',
  sv: 'Sects & Violets',
  experimental: 'Experimental',
  travellers: 'Travellers',
  fabled: 'Fabled',
  loric: 'Loric'
};

export const ROLES = [
  r('washerwoman','Washerwoman','townsfolk','tb','Recebe uma pista inicial sobre uma role boa específica em jogo.', {night:1, info:3}),
  r('librarian','Librarian','townsfolk','tb','Recebe uma pista inicial sobre Outsider; se não houver, aprende isso.', {night:1, info:3}),
  r('investigator','Investigator','townsfolk','tb','Recebe uma pista inicial sobre possível Minion entre dois jogadores.', {night:1, info:3}),
  r('chef','Chef','townsfolk','tb','Descobre quantos pares de jogadores maus estão sentados lado a lado.', {night:1, info:4}),
  r('empath','Empath','townsfolk','tb','A cada noite aprende quantos vizinhos vivos são maus.', {night:2, info:4}),
  r('fortune-teller','Fortune Teller','townsfolk','tb','Investiga dois jogadores à noite para saber se algum parece Demon.', {night:3, info:5}),
  r('undertaker','Undertaker','townsfolk','tb','À noite aprende a role de quem foi executado naquele dia.', {night:2, info:4}),
  r('monk','Monk','townsfolk','tb','Protege um jogador do Demon durante a noite.', {night:2, info:1}),
  r('ravenkeeper','Ravenkeeper','townsfolk','tb','Se morrer à noite, escolhe alguém e aprende sua role.', {night:1, info:4}),
  r('virgin','Virgin','townsfolk','tb','A primeira nomeação feita por Townsfolk pode executar imediatamente quem nomeou.', {difficulty:2, info:2}),
  r('slayer','Slayer','townsfolk','tb','Uma vez por jogo, tenta matar publicamente alguém que seja o Demon.', {difficulty:2, info:2}),
  r('soldier','Soldier','townsfolk','tb','Não morre por ataque direto do Demon.', {difficulty:1}),
  r('mayor','Mayor','townsfolk','tb','Pode vencer no fim se restarem três vivos sem execução; mortes noturnas podem desviar.', {difficulty:3}),
  r('butler','Butler','outsider','tb','Precisa seguir o voto de um mestre escolhido, reduzindo liberdade política.', {difficulty:1, evil:1}),
  r('drunk','Drunk','outsider','tb','Acha que é Townsfolk, mas sua habilidade não funciona.', {difficulty:3, evil:4, setup:true}),
  r('recluse','Recluse','outsider','tb','Pode parecer mau para habilidades, confundindo informações.', {difficulty:2, evil:2}),
  r('saint','Saint','outsider','tb','Se for executado, o time bom perde.', {difficulty:3, evil:3}),
  r('poisoner','Poisoner','minion','tb','A cada noite escolhe alguém para ficar envenenado e receber informação/efeito falso.', {night:3, evil:4}),
  r('spy','Spy','minion','tb','Vê o grimório e pode parecer bom para habilidades.', {night:2, evil:5}),
  r('scarlet-woman','Scarlet Woman','minion','tb','Pode virar Demon se o Demon morrer cedo.', {difficulty:2, evil:4}),
  r('baron','Baron','minion','tb','Altera a montagem adicionando Outsiders e removendo Townsfolk.', {difficulty:1, evil:4, setup:true}),
  r('imp','Imp','demon','tb','Mata à noite; pode se matar para passar o Demon para um Minion.', {night:2, evil:5}),

  r('grandmother','Grandmother','townsfolk','bmr','Aprende um jogador e sua role; se ele morrer pelo Demon, a Grandmother também morre.', {night:1, info:4}),
  r('sailor','Sailor','townsfolk','bmr','À noite escolhe alguém: um dos dois fica bêbado; o Sailor é difícil de matar.', {night:3, info:1}),
  r('chambermaid','Chambermaid','townsfolk','bmr','Escolhe dois jogadores vivos e aprende quantos acordaram naquela noite.', {night:3, info:4}),
  r('exorcist','Exorcist','townsfolk','bmr','Escolhe alguém; se for Demon, ele não age e sabe quem o bloqueou.', {night:3, info:2}),
  r('innkeeper','Innkeeper','townsfolk','bmr','Protege dois jogadores à noite, mas um deles fica bêbado.', {night:3, info:1}),
  r('gambler','Gambler','townsfolk','bmr','À noite tenta adivinhar a role de alguém; se errar, morre.', {night:3, info:3}),
  r('gossip','Gossip','townsfolk','bmr','Faz uma afirmação pública; se for verdadeira, uma morte extra pode ocorrer.', {night:1, info:3}),
  r('courtier','Courtier','townsfolk','bmr','Uma vez por jogo deixa uma role bêbada por alguns dias.', {night:2, info:1}),
  r('professor','Professor','townsfolk','bmr','Uma vez por jogo pode reviver um jogador bom morto.', {night:2, info:1}),
  r('minstrel','Minstrel','townsfolk','bmr','Quando um Minion morre por execução, todos ficam bêbados até o anoitecer seguinte.', {difficulty:3, info:2}),
  r('tea-lady','Tea Lady','townsfolk','bmr','Vizinhos bons podem ficar protegidos contra morte.', {difficulty:2, info:1}),
  r('pacifist','Pacifist','townsfolk','bmr','Execuções de jogadores bons podem falhar.', {difficulty:2, info:1}),
  r('fool','Fool','townsfolk','bmr','A primeira morte do Fool não acontece.', {difficulty:1}),
  r('goon','Goon','outsider','bmr','Quem o escolher primeiro à noite fica bêbado; o Goon muda de alinhamento.', {night:1, evil:2}),
  r('lunatic','Lunatic','outsider','bmr','Acha que é Demon, mas não é; pode receber informações falsas de Demon.', {night:2, evil:4}),
  r('tinker','Tinker','outsider','bmr','Pode morrer a qualquer momento por decisão do Storyteller.', {difficulty:1, evil:2}),
  r('moonchild','Moonchild','outsider','bmr','Ao morrer, escolhe um jogador; se for bom, ele pode morrer à noite.', {night:1, evil:2}),
  r('godfather','Godfather','minion','bmr','Sabe Outsiders em jogo e pode matar quando Outsider morre por execução.', {night:2, evil:5, setup:true}),
  r('devils-advocate','Devil\'s Advocate','minion','bmr','Escolhe alguém para não morrer por execução naquele dia.', {night:3, evil:4}),
  r('assassin','Assassin','minion','bmr','Uma vez por jogo mata alguém, ignorando proteção comum.', {night:2, evil:4}),
  r('mastermind','Mastermind','minion','bmr','Se o Demon morre por execução, pode haver mais um dia decisivo.', {difficulty:3, evil:4}),
  r('zombuul','Zombuul','demon','bmr','Morre falso uma vez e continua jogando; mata com ritmo reduzido.', {night:2, evil:5}),
  r('pukka','Pukka','demon','bmr','Envenena uma vítima antes dela morrer na noite seguinte.', {night:3, evil:5}),
  r('shabaloth','Shabaloth','demon','bmr','Pode matar dois por noite, mas às vezes ressuscita vítimas.', {night:3, evil:5}),
  r('po','Po','demon','bmr','Pode carregar poder e depois matar várias pessoas numa noite.', {night:2, evil:5}),

  r('clockmaker','Clockmaker','townsfolk','sv','Aprende a distância entre Demon e Minion mais próximos.', {night:1, info:4}),
  r('dreamer','Dreamer','townsfolk','sv','Escolhe alguém e aprende uma role boa e uma má possíveis para ele.', {night:3, info:5}),
  r('snake-charmer','Snake Charmer','townsfolk','sv','Escolhe alguém; se for Demon, troca de personagem e alinhamento com ele.', {night:3, info:4}),
  r('mathematician','Mathematician','townsfolk','sv','Aprende quantas habilidades funcionaram errado por bêbado/envenenado.', {night:2, info:4}),
  r('flowergirl','Flowergirl','townsfolk','sv','Aprende se o Demon votou durante o dia.', {night:2, info:4}),
  r('town-crier','Town Crier','townsfolk','sv','Aprende se um Minion nomeou durante o dia.', {night:2, info:4}),
  r('oracle','Oracle','townsfolk','sv','Aprende quantos mortos são maus.', {night:2, info:4}),
  r('savant','Savant','townsfolk','sv','Recebe duas informações por dia: uma verdadeira e uma falsa.', {difficulty:4, info:5}),
  r('seamstress','Seamstress','townsfolk','sv','Uma vez por jogo escolhe dois jogadores e aprende se têm mesmo alinhamento.', {night:2, info:4}),
  r('philosopher','Philosopher','townsfolk','sv','Escolhe uma habilidade de Townsfolk; se já existir, alguém pode ficar bêbado.', {night:2, info:3}),
  r('artist','Artist','townsfolk','sv','Uma vez por jogo faz uma pergunta sim/não ao Storyteller.', {difficulty:3, info:5}),
  r('juggler','Juggler','townsfolk','sv','No primeiro dia chuta roles de jogadores e aprende quantos acertou.', {night:1, info:5}),
  r('sage','Sage','townsfolk','sv','Se morrer pelo Demon, aprende um de dois possíveis Demons.', {night:1, info:4}),
  r('mutant','Mutant','outsider','sv','Se revelar ou sugerir sua própria condição, pode ser executado.', {difficulty:3, evil:2}),
  r('sweetheart','Sweetheart','outsider','sv','Quando morre, alguém fica bêbado permanentemente.', {difficulty:2, evil:3}),
  r('barber','Barber','outsider','sv','Quando morre, o Demon pode trocar personagens de dois jogadores.', {night:1, evil:3}),
  r('klutz','Klutz','outsider','sv','Ao morrer, escolhe alguém; se escolher mau, o bom perde.', {difficulty:3, evil:3}),
  r('evil-twin','Evil Twin','minion','sv','Tem um gêmeo bom conhecido; o bom perde se executar o gêmeo bom.', {difficulty:4, evil:5}),
  r('witch','Witch','minion','sv','Amaldiçoa alguém; se esse jogador nomear, morre.', {night:3, evil:4}),
  r('cerenovus','Cerenovus','minion','sv','Força alguém a agir como se fosse certa role, sob risco de execução.', {night:3, evil:4}),
  r('pit-hag','Pit-Hag','minion','sv','Muda personagens à noite, bagunçando a composição da partida.', {night:3, evil:5}),
  r('fang-gu','Fang Gu','demon','sv','Pode pular para um Outsider e transformar esse jogador em Demon.', {night:2, evil:5}),
  r('vigormortis','Vigormortis','demon','sv','Mata Minions mas preserva habilidade deles, envenenando vizinhos.', {night:2, evil:5}),
  r('no-dashii','No Dashii','demon','sv','Envenena os dois vizinhos vivos mais próximos.', {night:2, evil:5}),
  r('vortox','Vortox','demon','sv','Informações de Townsfolk são falsas; sem execução diária, o mal vence.', {night:2, evil:5}),

  r('acrobat','Acrobat','townsfolk','experimental','Pode morrer se um vizinho bom estiver bêbado ou envenenado.', {night:1, info:2}),
  r('alchemist','Alchemist','townsfolk','experimental','Recebe uma habilidade de Minion, mas joga pelo bem.', {night:2, info:2}),
  r('alsaahir','Alsaahir','townsfolk','experimental','Tenta declarar Demon e Minions; se acertar tudo, o bem vence.', {difficulty:4, info:4}),
  r('amnesiac','Amnesiac','townsfolk','experimental','Tem uma habilidade secreta criada pelo Storyteller e precisa deduzir qual é.', {difficulty:5, night:2, info:3}),
  r('atheist','Atheist','townsfolk','experimental','Se estiver em jogo, o Storyteller pode quebrar regras; executar o Storyteller pode vencer.', {difficulty:5, info:2}),
  r('balloonist','Balloonist','townsfolk','experimental','Recebe jogadores de tipos diferentes ao longo das noites.', {night:2, info:5}),
  r('banshee','Banshee','townsfolk','experimental','Se morrer, continua com algum impacto e pode votar/nominar de forma especial.', {difficulty:3, info:2}),
  r('bounty-hunter','Bounty Hunter','townsfolk','experimental','Aprende jogadores maus; em troca, um Townsfolk pode começar mau.', {night:2, info:5, setup:true}),
  r('cannibal','Cannibal','townsfolk','experimental','Ganha a habilidade do jogador executado, mas pode ficar envenenado se era mau.', {difficulty:4, night:2, info:3}),
  r('choirboy','Choirboy','townsfolk','experimental','Se o King morrer pelo Demon, aprende quem é o Demon.', {night:1, info:4}),
  r('cult-leader','Cult Leader','townsfolk','experimental','Pode mudar de alinhamento; se seguidores suficientes votarem juntos, o bem pode vencer.', {difficulty:4, info:1}),
  r('engineer','Engineer','townsfolk','experimental','Uma vez por jogo altera quais Minions/Demons existem.', {night:1, info:1}),
  r('farmer','Farmer','townsfolk','experimental','Quando morre à noite, outro jogador bom pode virar Farmer.', {night:1, info:1}),
  r('fisherman','Fisherman','townsfolk','experimental','Uma vez por jogo pede conselho útil ao Storyteller.', {difficulty:2, info:4}),
  r('general','General','townsfolk','experimental','Aprende um sentimento geral sobre qual time está vencendo.', {night:2, info:3}),
  r('high-priestess','High Priestess','townsfolk','experimental','Aprende com quem deveria falar para ajudar seu time.', {night:2, info:3}),
  r('huntsman','Huntsman','townsfolk','experimental','Procura a Damsel e pode transformá-la em Townsfolk.', {night:2, info:2}),
  r('king','King','townsfolk','experimental','À noite aprende uma role boa viva; o Demon sabe quem é o King.', {night:2, info:4}),
  r('knight','Knight','townsfolk','experimental','Aprende se há algum Demon entre jogadores próximos indicados pelo Storyteller.', {night:1, info:4}),
  r('lycanthrope','Lycanthrope','townsfolk','experimental','À noite escolhe alguém para matar; se escolher bom, pode impedir mortes do mal.', {night:3, info:2}),
  r('magician','Magician','townsfolk','experimental','Confunde informação inicial do mal, parecendo Minion/Demon para eles.', {difficulty:2, info:1}),
  r('nightwatchman','Nightwatchman','townsfolk','experimental','Uma vez por jogo faz alguém aprender que você é Nightwatchman.', {night:1, info:2}),
  r('noble','Noble','townsfolk','experimental','Aprende três jogadores, exatamente um deles é mau.', {night:1, info:5}),
  r('pixie','Pixie','townsfolk','experimental','Vê uma role boa em jogo; se agir como ela, pode ganhar a habilidade depois.', {difficulty:3, info:3}),
  r('poppy-grower','Poppy Grower','townsfolk','experimental','Impede que Minions e Demon saibam quem são seus aliados no início.', {difficulty:3, info:1}),
  r('preacher','Preacher','townsfolk','experimental','Escolhe jogadores para remover habilidades de Minion; Minions afetados sabem.', {night:3, info:2}),
  r('princess','Princess','townsfolk','experimental','Se for indicada para execução, pode dar ao bem um caminho alternativo de vitória.', {difficulty:3, info:1}),
  r('shugenja','Shugenja','townsfolk','experimental','Aprende uma direção onde existe algum jogador mau.', {night:1, info:4}),
  r('steward','Steward','townsfolk','experimental','Aprende um jogador bom.', {night:1, info:3}),
  r('village-idiot','Village Idiot','townsfolk','experimental','Múltiplos podem existir; escolhe alguém e aprende alinhamento, mas um deles fica bêbado.', {night:3, info:4}),
  r('damsel','Damsel','outsider','experimental','Se um Minion identificar publicamente a Damsel, o mal vence.', {difficulty:4, evil:4}),
  r('golem','Golem','outsider','experimental','A primeira nomeação mata o alvo se não for Demon; depois não pode nomear.', {difficulty:2, evil:2}),
  r('hatter','Hatter','outsider','experimental','Quando morre, o mal pode trocar Minions/Demons por outros do script.', {night:1, evil:3}),
  r('heretic','Heretic','outsider','experimental','Inverte o resultado final da partida.', {difficulty:5, evil:5}),
  r('hermit','Hermit','outsider','experimental','Pode virar Outsider diferente se não for escolhido em montagem específica.', {difficulty:3, evil:2}),
  r('ogre','Ogre','outsider','experimental','Escolhe um jogador; seu alinhamento passa a seguir o dele.', {night:1, evil:2}),
  r('plague-doctor','Plague Doctor','outsider','experimental','Ao morrer, o Storyteller ganha uma habilidade de Minion.', {night:1, evil:4}),
  r('politician','Politician','outsider','experimental','Pode ganhar com o mal se for o maior responsável pela vitória deles.', {difficulty:4, evil:3}),
  r('puzzlemaster','Puzzlemaster','outsider','experimental','Um jogador fica bêbado; uma vez tenta adivinhar quem é.', {difficulty:3, evil:3}),
  r('snitch','Snitch','outsider','experimental','Minions recebem bluffs extras, facilitando mentira do mal.', {difficulty:1, evil:3}),
  r('zealot','Zealot','outsider','experimental','Tem restrições fortes de voto/nominação, atrapalhando a cidade.', {difficulty:2, evil:2}),
  r('boffin','Boffin','minion','experimental','Dá ao Demon uma habilidade boa, criando combinações fortes.', {night:1, evil:5}),
  r('boomdandy','Boomdandy','minion','experimental','Se executado, cria uma votação explosiva e rápida que pode decidir o jogo.', {difficulty:4, evil:4}),
  r('fearmonger','Fearmonger','minion','experimental','Escolhe um alvo; se esse alvo for executado, o mal vence.', {night:3, evil:5}),
  r('goblin','Goblin','minion','experimental','Se for executado depois de alegar Goblin, o mal vence.', {difficulty:4, evil:4}),
  r('harpy','Harpy','minion','experimental','Liga dois jogadores; se não cumprirem a condição social, um pode morrer.', {night:3, evil:4}),
  r('marionette','Marionette','minion','experimental','É Minion mas pensa ser uma role boa, normalmente vizinha do Demon.', {difficulty:4, evil:4, setup:true}),
  r('mezepheles','Mezepheles','minion','experimental','Pode converter um jogador bom para o mal usando uma palavra secreta.', {night:1, evil:5}),
  r('organ-grinder','Organ Grinder','minion','experimental','Torna votos secretos ou difíceis de rastrear enquanto estiver vivo.', {difficulty:4, evil:4}),
  r('psychopath','Psychopath','minion','experimental','Pode matar durante o dia e talvez sobreviver se for escolhido errado.', {difficulty:4, evil:5}),
  r('summoner','Summoner','minion','experimental','No início não há Demon; depois escolhe alguém para virar Demon.', {night:2, evil:5}),
  r('vizier','Vizier','minion','experimental','É mau conhecido e tem influência pública forte sobre execuções.', {difficulty:5, evil:5}),
  r('widow','Widow','minion','experimental','Vê o grimório e envenena alguém; um bom sabe que há Widow.', {night:2, evil:5}),
  r('wizard','Wizard','minion','experimental','Manipula informação/efeitos por mágica, criando caos avançado.', {difficulty:5, night:2, evil:4}),
  r('wraith','Wraith','minion','experimental','Pode ter ações noturnas especiais e mexe com comunicação/olhos abertos.', {difficulty:5, night:2, evil:4}),
  r('xaan','Xaan','minion','experimental','Faz envenenamento temporal e previsível para confundir leituras.', {night:2, evil:4}),
  r('al-hadikhia','Al-Hadikhia','demon','experimental','Escolhe vítimas; jogadores podem aceitar morrer ou sobreviver, mudando o fim da noite.', {night:4, evil:5}),
  r('kazali','Kazali','demon','experimental','Escolhe seus Minions no início e mata à noite.', {night:2, evil:5, setup:true}),
  r('legion','Legion','demon','experimental','Vários jogadores maus podem ser Legion; votação vira o centro da partida.', {difficulty:5, night:1, evil:5}),
  r('leviathan','Leviathan','demon','experimental','Partida tem limite rígido de dias; execuções erradas podem condenar o bem.', {difficulty:5, evil:5}),
  r('lil-monsta','Lil\' Monsta','demon','experimental','Bebê-monstro é segurado por Minions; quem o segura funciona como Demon.', {night:3, evil:5}),
  r('lleech','Lleech','demon','experimental','Hospeda-se em alguém; só morre de verdade quando o hospedeiro morre.', {night:2, evil:5}),
  r('lord-of-typhon','Lord of Typhon','demon','experimental','Cria uma equipe má agrupada em torno dele na ordem dos assentos.', {night:2, evil:5, setup:true}),
  r('ojo','Ojo','demon','experimental','Escolhe uma role para matar quem a possui.', {night:3, evil:5}),
  r('riot','Riot','demon','experimental','Vários Riots podem existir; nomeações e execuções definem mortes rápidas.', {difficulty:5, night:1, evil:5}),
  r('yaggababble','Yaggababble','demon','experimental','Tem uma frase secreta que pode causar mortes extras quando dita.', {difficulty:5, night:1, evil:5}),

  r('bureaucrat','Bureaucrat','traveller','travellers','Aumenta o peso do voto de alguém temporariamente.', {difficulty:2}),
  r('thief','Thief','traveller','travellers','Reduz o peso do voto de alguém temporariamente.', {difficulty:2}),
  r('gunslinger','Gunslinger','traveller','travellers','Pode matar um dos jogadores que votaram numa nomeação.', {difficulty:3}),
  r('scapegoat','Scapegoat','traveller','travellers','Pode ser executado no lugar de alguém do mesmo alinhamento.', {difficulty:2}),
  r('beggar','Beggar','traveller','travellers','Precisa pedir votos dos mortos para votar com força.', {difficulty:2}),
  r('apprentice','Apprentice','traveller','travellers','Recebe uma habilidade de Townsfolk ou Outsider.', {difficulty:3}),
  r('matron','Matron','traveller','travellers','Controla lugares/assentos e limita conversas privadas.', {difficulty:3}),
  r('judge','Judge','traveller','travellers','Uma vez por jogo interfere no resultado de uma votação.', {difficulty:3}),
  r('bishop','Bishop','traveller','travellers','Mexe em quem pode nomear, deixando nomeações menos previsíveis.', {difficulty:3}),
  r('voudon','Voudon','traveller','travellers','Muda a influência dos mortos em votos e nomeações.', {difficulty:4}),
  r('bone-collector','Bone Collector','traveller','travellers','Permite que um morto use sua habilidade novamente por um período.', {difficulty:3}),
  r('barista','Barista','traveller','travellers','Potencializa ou limpa a habilidade de alguém por uma noite/dia.', {difficulty:3}),
  r('harlot','Harlot','traveller','travellers','Visita alguém à noite para aprender sua role, com risco de morte.', {night:2, difficulty:3}),
  r('butcher','Butcher','traveller','travellers','Permite uma segunda execução no mesmo dia em certas condições.', {difficulty:3}),
  r('deviant','Deviant','traveller','travellers','Tem uma regra social secreta; quebrá-la pode causar punição.', {difficulty:4}),
  r('cacklejack','Cacklejack','traveller','experimental','Traveller experimental caótico, usado para alterar ações/noturnos em mesa avançada.', {difficulty:5, night:2}),
  r('gangster','Gangster','traveller','experimental','Traveller experimental com pressão social e ameaça direta entre jogadores.', {difficulty:4}),
  r('gnome','Gnome','traveller','experimental','Traveller experimental que se vincula a outro jogador e muda incentivos de equipe.', {difficulty:4}),

  r('angel','Angel','fabled','fabled','Protege iniciantes de serem eliminados cedo demais.', {difficulty:1}),
  r('buddhist','Buddhist','fabled','fabled','Ajuda a equilibrar jogos com jogadores experientes e novatos.', {difficulty:1}),
  r('djinn','Djinn','fabled','fabled','Ativa jinxes/regras especiais para combinações problemáticas de personagens.', {difficulty:2}),
  r('doomsayer','Doomsayer','fabled','fabled','Permite mortes públicas voluntárias para acelerar ou ajustar a partida.', {difficulty:2}),
  r('fiddler','Fiddler','fabled','fabled','Cria uma decisão final direta entre dois jogadores quando a partida emperra.', {difficulty:2}),
  r('fibbin','Fibbin','fabled','fabled','Permite que o Storyteller dê informação falsa extra em contexto controlado.', {difficulty:3}),
  r('hells-librarian','Hell\'s Librarian','fabled','fabled','Pune comunicação excessiva ou barulho, ajudando a manter ordem.', {difficulty:1}),
  r('revolutionary','Revolutionary','fabled','fabled','Dois jogadores podem conhecer os alinhamentos um do outro para acessibilidade.', {difficulty:1}),
  r('sentinel','Sentinel','fabled','fabled','Ajusta a quantidade de Outsiders para balancear o script.', {difficulty:1}),
  r('spirit-of-ivory','Spirit of Ivory','fabled','fabled','Limita quantos jogadores bons podem virar maus.', {difficulty:2}),
  r('storm-catcher','Storm Catcher','fabled','fabled','Faz uma role específica ter proteção/centralidade em scripts avançados.', {difficulty:2}),
  r('toymaker','Toymaker','fabled','fabled','Obriga o Demon a pular mortes em jogos pequenos ou ajustes específicos.', {difficulty:2}),
  r('deus-ex-fiasco','Deus ex Fiasco','fabled','experimental','Regra experimental para situações caóticas/inesperadas do Storyteller.', {difficulty:5}),
  r('ferryman','Ferryman','fabled','experimental','Permite devolver votos fantasma ou ajustar mortos em condições especiais.', {difficulty:4}),

  r('big-wig','Big Wig','loric','loric','Regra avançada de Storyteller para efeitos públicos e alterações sociais.', {difficulty:5}),
  r('bootlegger','Bootlegger','loric','loric','Autoriza regras caseiras anunciadas antes da partida.', {difficulty:3}),
  r('gardener','Gardener','loric','loric','Permite ao Storyteller escolher/distribuir roles específicas.', {difficulty:3}),
  r('god-of-ug','God of Ug','loric','loric','Regra avançada de humor/caos, usada apenas em mesas que aceitam maluquice.', {difficulty:5}),
  r('hindu','Hindu','loric','loric','Regra avançada de alteração/condição especial do Storyteller.', {difficulty:5}),
  r('knaves','Knaves','loric','loric','Regra avançada que muda incentivos e pode bagunçar confiança pública.', {difficulty:5}),
  r('pope','Pope','loric','loric','Regra avançada que permite duplicações/efeitos incomuns em scripts especiais.', {difficulty:5}),
  r('tor','Tor','loric','loric','Regra avançada de script; manter como referência até refinarmos.', {difficulty:5}),
  r('ventriloquist','Ventriloquist','loric','loric','Regra avançada de comunicação/voz usada em scripts muito específicos.', {difficulty:5}),
  r('zenomancer','Zenomancer','loric','loric','Regra avançada de manipulação para mesas experientes.', {difficulty:5})
];

export const SCRIPT_PRESETS = [
  {
    id: 'tb',
    name: 'Trouble Brewing',
    subtitle: 'Base simples para aprender',
    description: 'A seleção mais limpa: investigação, mentira e um Demon direto.',
    editions: ['tb'],
    recommended: true
  },
  {
    id: 'bmr',
    name: 'Bad Moon Rising',
    subtitle: 'Morte, proteção e blefe pesado',
    description: 'Mais mortes e sobrevivências estranhas. Melhor para mesa que já conhece o jogo.',
    editions: ['bmr']
  },
  {
    id: 'sv',
    name: 'Sects & Violets',
    subtitle: 'Informação forte e caos lógico',
    description: 'Muitas informações, mudanças de role e veneno. Exige mais atenção.',
    editions: ['sv']
  },
  {
    id: 'experimental',
    name: 'Experimental',
    subtitle: 'Roles soltas para scripts próprios',
    description: 'Peças avançadas para testar ideias e combinações.',
    editions: ['experimental']
  },
  {
    id: 'all',
    name: 'Todas as roles',
    subtitle: 'Banco completo do MVP',
    description: 'Mostra tudo que está cadastrado no guia, incluindo Travellers e regras.',
    editions: ['tb', 'bmr', 'sv', 'experimental', 'travellers', 'fabled', 'loric']
  }
];

export const PLAYER_ROLE_TEAMS = ['townsfolk', 'outsider', 'minion', 'demon'];
export const GUIDE_TEAMS = ['townsfolk', 'outsider', 'minion', 'demon', 'traveller', 'fabled', 'loric'];
